### ISSUE TITLE
转换成文字时出现错误

### ISSUE THREAD

**Issue by summer506hai** [ouening/python-text-recognition#1]
选择图片后，点击转换成文字 出现报错
Traceback (most recent call last):
  File "......   python-text-recognition-master/src/baidu-api.py", line 967, in convertButton_callback
    txt=res['words_result']
KeyError: 'words_result'

程序退出
Process finished with exit code -1073740791 (0xC0000409)

**Comment by summer506hai** [comment]
> 选择图片后，点击转换成文字 出现报错
> Traceback (most recent call last):
> File "...... python-text-recognition-master/src/baidu-api.py", line 967, in convertButton_callback
> txt=res['words_result']
> KeyError: 'words_result'
> 
> 程序退出
> Process finished with exit code -1073740791 (0xC0000409)

应该是鉴权失败问题

**Comment by Wud1** [comment]
@summer506hai  我也遇到了同样的问题，请问你解决了吗？

**Comment by ouening** [comment]
这个程序之前不完善，用的我自己申请的ID和秘钥，被人玩坏了，简化后的新版本没有放出，可以自己在百度云申请图像文本识别App  ID

**Comment by Wud1** [comment]
@ouening 我申请了，然后在你代码里面把id更改为自己的之后，运行baidu-api 的时候出来的GUI框 还是显示的是你之前的。

**Comment by summer506hai** [comment]
> @summer506hai 我也遇到了同样的问题，请问你解决了吗？
@Wud1 
解决了，自己申请一个ID，把代码改下就可以 。
appid，apikey，screet key 可以自行填写； https://github.com/summer506hai/python-text-recognition  这是我改的
